import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {

    in property <string> results: "";
    in-out property <bool> opencurtain;
    callback  divide-income(string);

    background: #313e50;
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row{
            Text {
                text: "Enter Total income";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 900;
            }
        }
        
        Row{
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 16px;
                placeholder-text: "Enter your income";
                height: 35px;
            }
        }

        Row{
            Button {
                
                height: 35px;
                text: "Calculate";
                primary: true;
                clicked => {
                    root.opencurtain = !root.opencurtain;
                    divide-income(income.text)
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 100px;
                    background: #cae5f0;
                    Text {
                        color: black;
                        font-size: 16px;
                        font-family: "Arial";
                        font-weight: 700;
                        text: root.results;
                    }

                    // Left rectangle
                    Rectangle {
                        background: #333333;
                        x: 0;
                        width: opencurtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                            duration: 250ms; easing: ease-in;
                        }
                    }

                    // Right rectangle
                    Rectangle {
                        background: #333333;
                        x: opencurtain ? parent.width : parent.width / 2;
                        width: opencurtain ? 0px : parent.width / 2;
                        height: parent.height;
                        animate width {
                            duration: 250ms; easing: ease-in;
                        }
                        animate x {
                            duration: 250ms; easing: ease-in;     
                        }
                    }
                }
            }
        }
    }
}
